# TensorFlow 基礎介紹

TensorFlow 是一個由 Google 開發的機器學習平台，主要用於深度學習應用的開發和部署。它提供了豐富的工具集，從基礎層級的數學運算（如矩陣運算）到高層次的神經網絡構建，無論你是剛入門的初學者還是有經驗的研究者，TensorFlow 都是一個強大且靈活的工具。

TensorFlow 能夠讓開發者方便地構建、訓練和部署深度學習模型。它被廣泛應用於影像分類、語音辨識、自然語言處理等領域，並支持多種計算平台，包括 CPU、GPU、以及 TPU，讓運算的效能能夠靈活擴展。

首先，我們需要安裝並匯入相關套件。如果你還沒有安裝 TensorFlow，可以使用以下指令來安裝：

```sh
pip install tensorflow
```

## 1. 張量（Tensor）
在 TensorFlow 中，張量（Tensor）是進行所有運算的基本單位。張量的概念與 NumPy 陣列類似，但張量具備更強的擴展性，特別適合 GPU 加速的運算需求。

### 1.1 張量的基本操作

我們可以使用 `tf.constant()` 來創建一個靜態張量，或者使用 `tf.Variable()` 來創建一個可變張量。

In [2]:
import tensorflow as tf
import numpy as np

# 建立一個靜態張量
a = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
print(a)

# 建立一個 NumPy 陣列並轉換為張量
b = tf.constant(np.array([1, 2, 3, 4, 5]), dtype=tf.float32)
print(b)

# 建立一個可變張量
c = tf.Variable([1, 2, 3, 4, 5], dtype=tf.float32)
print(c)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>


TensorFlow 張量和 NumPy 陣列不同之處在於，張量可以分為兩種：一種是**無法更改值的 Tensor**，另一種是**可以更改值的 Variable**。在神經網路中，所有可訓練的變數都以 Variable 形式存在，這樣才能在訓練過程中進行數值更新。

### 1.2 張量與 NumPy 的互動

張量可以輕鬆地與 NumPy 陣列相互轉換，這對於需要在 TensorFlow 與其他數值計算工具之間交互時非常有用：

In [3]:
# 將 TensorFlow 張量轉換為 NumPy 陣列
d = a.numpy()
print(d)

# 將 NumPy 陣列轉換為張量
e = tf.convert_to_tensor(np.array([5, 4, 3, 2, 1]), dtype=tf.float32)
print(e)

[1. 2. 3. 4. 5.]
tf.Tensor([5. 4. 3. 2. 1.], shape=(5,), dtype=float32)


### 1.3 張量的性質
張量具有以下幾個重要的性質：

1. **形狀（Shape）**：張量的形狀代表其在每個維度上的大小。形狀可以通過 `tensor.shape` 來獲取，這對於理解張量結構非常重要。
2. **資料型別（Data Type）**：張量中的每個元素都具有相同的資料型別，例如 float32、int32 等，可以通過 `tensor.dtype` 來獲取。
3. **設備（Device）**：張量可以被分配到不同的設備上進行計算，例如 CPU 或 GPU，可以通過 `tensor.device` 查看張量所在的設備。

In [4]:
tensor = tf.constant([[1, 2], [3, 4], [5, 6]])
print(tensor.shape)  # 結果為 (3, 2)，表示張量有 3 個列和 2 個行

(3, 2)


In [5]:
tensor = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
print(tensor.dtype)  # 結果為 float32

<dtype: 'float32'>


In [6]:
with tf.device('/CPU:0'):
    tensor = tf.constant([1, 2, 3])
print(tensor.device)  # 顯示張量所在的設備，例如 '/job:localhost/replica:0/task:0/device:CPU:0'

/job:localhost/replica:0/task:0/device:CPU:0


### 1.4 張量的數學運算
張量支援多種數學運算，例如加減乘除、矩陣乘法、指數運算等，這些操作可以非常簡單地透過 TensorFlow 提供的函數來實現。

以下是一些常見的張量運算範例：

In [5]:
# 建立兩個張量
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# 張量加法
c = tf.add(a, b)
print(c)  # 結果為 [[ 6  8]
          #        [10 12]]

# 張量減法
d = tf.subtract(a, b)
print(d)  # 結果為 [[-4 -4]
          #        [-4 -4]]

# 張量乘法（逐元素相乘）
e = tf.multiply(a, b)
print(e)  # 結果為 [[ 5 12]
          #        [21 32]]

# 矩陣乘法
f = tf.matmul(a, b)
print(f)  # 結果為 [[19 22]
          #        [43 50]]

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## 2. 自動計算微分值
在深度學習演算法中，模型的權重更新是非常重要的環節，這需要對變數進行偏微分計算。
TensorFlow 提供了一個強大的工具來進行自動微分，即 `tf.GradientTape()`。這使得神經網路的訓練過程變得非常簡單，因為你可以輕鬆地計算導數並更新模型參數。

### 2.1 使用 `tf.GradientTape()` 進行微分
以下是如何使用 `tf.GradientTape()` 來進行自動微分的例子：

>若此函數 $f(x) = x^2$ 對 $x$ 做偏微分，則能得到 $f^\prime(x) = 2*x$
>
>將 $x = 3$ 代入函數，得到 $f(x)=9$，$f^\prime(x) = 6$

In [3]:
# 自動微分範例
x = tf.Variable(3.0)

def f(x):
    return x**2

with tf.GradientTape() as tape:
    y = f(x)

dy_dx = tape.gradient(y, x) 
print(dy_dx)  # 結果應該是 6.0，因為 y = x^2 對 x 的導數為 2*x

tf.Tensor(6.0, shape=(), dtype=float32)


在上述程式碼中，我們展示了如何使用 TensorFlow 的 `tf.GradientTape()` 進行自動微分。首先，我們定義了一個變數 x，並將其初始值設定為 3.0。接著，我們定義了一個函數 f(x)，它返回 x 的平方。在 `with tf.GradientTape() as tape:` 這段程式中，我們計算了 f(x)，即 `y = x**2`。使用 `tape.gradient(y, x)`，我們計算出 y 對 x 的導數，結果為 6.0，因為 `y = x^2` 對應的導數為 `2*x`，當 x=3 時，導數的值為 6.0。

這種自動微分的方式，對於計算複雜神經網路模型的梯度尤為重要，讓我們可以在訓練過程中更新權重，最小化損失。

## 3. 模型建置以及訓練
在 TensorFlow 中，我們可以通過高階 API（如 tf.keras）來快速構建和訓練模型。

### 3.1 使用 Keras 來建構模型
以下是一個簡單的線性迴歸模型的構建和訓練過程。這段程式碼展示了如何使用 tf.keras 構建並訓練一個簡單的線性迴歸模型，包括如何編譯模型、設定優化器和損失函數、提供訓練數據，以及最終進行預測。

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# 建立一個簡單的順序模型
model = Sequential([
    Dense(1, input_shape=(1,), activation='linear')
])

# 編譯模型，設定損失函數和優化器
model.compile(optimizer=SGD(learning_rate=0.01), loss='mse')

# 建立一些訓練數據
X_train = np.array([1, 2, 3, 4, 5], dtype=np.float32)
y_train = np.array([2, 4, 6, 8, 10], dtype=np.float32)

# 訓練模型
model.fit(X_train, y_train, epochs=100)

# 使用模型進行預測
print(model.predict([6]))  # 應該接近於 12

Epoch 1/100
1/1 [==============================] - 0s 186ms/step - loss: 14.7342
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 8.5930
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 5.0142
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 2.9285
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 1.7131
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 1.0048
Epoch 7/100
1/1 [==============================] - 0s 3ms/step - loss: 0.5919
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3513
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2110
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1293
Epoch 11/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0816
Epoch 12/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0537
Epoch 13/100
1/1 [==============================] - 0s 2ms